# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oL2gFBK5sTCTmlqhdNTU3e0h8GOBri2A
"""

# ============================================
# Agentic AI – Autonomous Task-Oriented AI Agent
# ============================================

import json

# ------------------------------------------------
# TOOL 1: Search Tool (Mock Research Paper Search)
# ------------------------------------------------
def search_papers(query):
    """
    Simulates searching recent AI research papers on agriculture
    """
    papers = [
        {
            "title": "AI-Based Crop Yield Prediction Using Deep Learning",
            "year": 2024,
            "content": "This paper proposes deep learning models to predict crop yield using soil and weather data."
        },
        {
            "title": "Machine Learning for Precision Agriculture",
            "year": 2023,
            "content": "The study discusses machine learning techniques for smart irrigation and fertilizer management."
        },
        {
            "title": "Computer Vision Applications in Smart Agriculture",
            "year": 2023,
            "content": "This research explores computer vision methods to detect crop diseases and monitor plant health."
        }
    ]
    return papers


# ------------------------------------------------
# TOOL 2: Summarization Tool
# ------------------------------------------------
def summarize_paper(paper):
    """
    Generates a short summary of a research paper
    """
    return paper["content"][:120] + "..."


# ------------------------------------------------
# TOOL 3: Storage Tool (JSON Output)
# ------------------------------------------------
def store_output(data):
    """
    Stores final summarized output in JSON format
    """
    with open("sample_output.json", "w") as file:
        json.dump(data, file, indent=4)


# ------------------------------------------------
# MEMORY HANDLER
# ------------------------------------------------
def save_memory(memory_data):
    """
    Saves memory/context of processed papers
    """
    with open("memory.json", "w") as file:
        json.dump(memory_data, file, indent=4)


# ------------------------------------------------
# AGENT LOGIC (Planning + Execution)
# ------------------------------------------------
def agentic_ai(user_goal):
    print("User Goal Received:")
    print(user_goal)
    print("-" * 50)

    # STEP 1: Task Decomposition (Planning)
    plan = [
        "Search for recent AI research papers on agriculture",
        "Select top 3 relevant papers",
        "Summarize each paper",
        "Store summaries in structured format"
    ]

    print("Agent Plan:")
    for step in plan:
        print("•", step)
    print("-" * 50)

    # STEP 2: Search Papers
    papers = search_papers("AI agriculture")

    # STEP 3: Select Top 3 Papers
    top_papers = papers[:3]

    # STEP 4: Summarize Papers
    final_results = []
    processed_titles = []

    for paper in top_papers:
        summary = summarize_paper(paper)
        final_results.append({
            "title": paper["title"],
            "year": paper["year"],
            "summary": summary
        })
        processed_titles.append(paper["title"])

    # STEP 5: Store Output
    store_output(final_results)

    # STEP 6: Save Memory
    save_memory({
        "processed_papers": processed_titles
    })

    print("Task completed successfully!")
    print("Output saved to sample_output.json")
    print("Memory saved to memory.json")


# ------------------------------------------------
# RUN AGENT
# ------------------------------------------------
if __name__ == "__main__":
    goal = "Find the top 3 recent AI research papers on agriculture, summarize them, and store the output in a structured format."
    agentic_ai(goal)